### ISSUE TITLE
Some improvements to make

### ISSUE THREAD

**Issue by RVxLab** [RVxLab/laravel-enum-cast#1]
- Don't create an `EnumCaster` instance when it's not needed
- Add `$enums` next to `$enumCasts` and deprecate `$enumCasts` (to be more in line with Laravel's naming convention)
- Add `null` checks, just to be safe

**Comment by kminek** [comment]
maybe its worth considering extending base enum class from `myclabs/php-enum` and implementing required interface methods there? it would simplify usage as you would only need to put key in `casts` array (you wouldnt need a trait and `$enumCasts` property) and extend app enums classes from this base one

**Comment by RVxLab** [comment]
That’s not what I’m going for what this package. 

The point of this package is to have a (somewhat) loose coupling between models and enum classes so that changes like that aren’t needed at all. This way it’s flexible.

**Comment by kminek** [comment]
well in my opinion you can sacrifice some coupling in order to ease library usage. you wont be switching enum classes in your app anyways in 95% of cases. so first you create base class for all your enums (based on the example from Laravel's docs):

```php
use Illuminate\Contracts\Database\Eloquent\Castable;
use Illuminate\Contracts\Database\Eloquent\CastsAttributes;
use MyCLabs\Enum\Enum;

abstract class CastableEnum extends Enum implements Castable
{
    public static function castUsing(array $arguments)
    {
        $nullable = in_array('nullable', $arguments, true) ? true : false;

        return new class(static::class, $nullable) implements CastsAttributes {
            protected $className;

            protected $nullable;

            public function __construct(string $className, bool $nullable)
            {
                $this->className = $className;
                $this->nullable = $nullable;
            }

            public function get($model, $key, $value, $attributes)
            {
                if ($this->nullable && (null === $value)) {
                    return $value;
                }

                $className = $this->className;

                return new $className($value);
            }

            public function set($model, $key, $value, $attributes)
            {
                if ($this->nullable && (null === $value)) {
                    return $value;
                }

                $enum = $value;

                return $enum->getValue();
            }
        };
    }
}
```

then you just extend this base class:

```php
class CarMake extends CastableEnum
{
    public const VOLKSWAGEN = 'volkswagen';
    public const BMW = 'bmw';
}
```

and finally you hook it into the model:

```php
protected $casts = [
    'make' => CarMake::class,
];
```

or if you want to allow `null`-s also:

```php
protected $casts = [
    'make' => CarMake::class.':nullable',
];
```

**Comment by RVxLab** [comment]
While this is probably not how I would do it, this is a way I really didn't think of doing and could prove useful. I'll think about using this for a 2.0 release which I'm planning on doing with PHP 8.1

Thanks for your input, greatly appreciated!
